FROM nvidia/cuda:12.4.0-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y python3 python3-pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt

CMD ["bash", "-c", "vllm serve Qwen/Qwen2.5-1.5B-Instruct --port 8000 --enable-auto-tool-choice --tool-call-parser hermes"]